import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF4E86F7),
  onPrimary: Colors.white,
  primaryContainer: Color(0xFF4E86F7),
  onPrimaryContainer: Colors.white,
  secondary: Color(0xFFFEB935),
  onSecondary: Color(0xFFDFFBF7),
  onSecondaryContainer: Color(0xFF1D192B),
  tertiary: Color(0xFF555555),
  onTertiary: Color(0xFFA4ACB9),
  tertiaryContainer: Color(0xFFFFD8E4),
  onTertiaryContainer: Color(0xFFFFDE9F),
  error: Color(0xFFFF3E57),
  errorContainer: Color(0xFFFFDAD4),
  onErrorContainer: Color(0xFF410001),
  onError: Color(0xFFFFDAD4),
  background: Color(0xFFFBFDFD),
  onBackground: Color(0xFF191C1D),
  surface: Color(0xFFFFFBFE),
  onSurface: Color(0xFF1C1B1F),
  // surfaceVariant: Color(0xFFE9DFEB),
  surfaceVariant: Color(0xFFF0F0F0),
  secondaryContainer: Color(0xFFE9DFEB),
  onSurfaceVariant: Color(0xFF49454F),
  outline: Color(0xFFC1C7D0),
  outlineVariant: Color(0xFFADAEB2),
  onInverseSurface: Color(0xFFF4EFF4),
  inverseSurface: Color(0xFF313033),
  inversePrimary: Color(0xFFD0BCFF),
  shadow: Color(0xFF000000),
);
